[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/agent",
    # "pallets/action",
	# "pallets/action/rpc",
	# "pallets/action/rpc/runtime-api",
    "runtime",
]
[profile.release]
panic = "unwind"
